1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [3]:
#generate the 3D dataset
import numpy as np
import pandas as pd
 
rng = np.random.default_rng(12341234) #random generator with seed

mean_1 = 0           #parameters
mean_2 = 0
var_1 = 1
var_2 = 3
coeff_3 = [2, 1]

x_1 = rng.normal(loc=mean_1, scale=var_1, size=1000)
x_2 = rng.normal(loc=mean_2, scale=var_2, size=1000)
x_3 = coeff_3[0]*x_1 + coeff_3[1]*x_2

#create the pandas dataframe
df = pd.DataFrame(
    { 'x_1' : x_1-mean_1,
      'x_2' : x_2-mean_2,
      'x_3' : x_3-(coeff_3[0]*mean_1)-(coeff_3[1]*mean_2),
    }
    )

#find the eigenvectors and the eigenvalues of the covariance matrix of the dataset
from scipy import linalg as la

CovMat = df.cov() #compute the covariance matrix
print(np.shape(CovMat))
print(la.det(CovMat), '\n')
l, a = la.eig(CovMat) #compute eigenvalues and eigenvectors
print("eigenvalues: ", l, '\n') 
print("eigenvectors: ", '\n' , a)

(3, 3)
-2.0955894659884562e-14 

eigenvalues:  [ 2.04725639e+01+0.j -1.70474000e-15+0.j  2.64835883e+00+0.j] 

eigenvectors:  
 [[-0.0776313   0.81649658 -0.57210726]
 [-0.62305413  0.40824829  0.6671858 ]
 [-0.77831673 -0.40824829 -0.47702872]]


In [2]:
#Find the eigenvectors and eigenvalues using SVD. Check that the two procedures yield to same result
U, spectrum, Vt = la.svd(CovMat)
print(spectrum)
print(spectrum == l)

[2.04725639e+01 2.64835883e+00 1.20007951e-15]
[False False False]


2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset

In [ ]:
# get the dataset and its description on the proper data directory
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P ~/data/
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P ~/data/ 